### ISSUE TITLE
Server error: RuntimeIOException: Failed to get file system for path: s3://warehouse/db/table/metadata/00000-8c5d0bdc-8cb4-428e-9c14-b69515f50c1e.metadata.json

### ISSUE THREAD

**Issue by ming12713** [cloudcheflabs/iceberg-rest-catalog#2]
hi, i follow [https://itnext.io/easy-way-to-move-iceberg-data-using-iceberg-rest-catalog-8fb74e630a43](url) install rest server and use spark sql create table ,encountered the following problem. Could you please help me take a look?

![Screenshot from 2023-05-25 13-27-43](https://github.com/cloudcheflabs/iceberg-rest-catalog/assets/5196113/fca73ca5-a4bf-4783-b9db-fc9a5b0caf37)

### rest server conf
```
restCatalog:
  token: "123456"
  warehouse: "s3://warehouse/"
  s3: 
    accessKey: "minio"
    secretKey: "minio"
    endpoint: "http://10.0.162.26:39999/api/v1/s3"
  jdbc:
    url: "jdbc:mysql://mysql:3306/rest_catalog?useSSL=false&createDatabaseIfNotExist=true"
    user: "root"
    password: "4XVQRr9h0L"
```
### spark configuration

```
# spark hadoop fs
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.impl  org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint.region cn-east-1
spark.hadoop.fs.s3a.access.key  minio
spark.hadoop.fs.s3a.secret.key  minio
spark.hadoop.fs.s3a.endpoint    http://10.0.162.26:39999/api/v1/s3
spark.hadoop.fs.s3a.bucket.probe  0
spark.hadoop.fs.s3a.change.detection.version.required  false
spark.hadoop.fs.s3a.change.detection.mode  none
spark.hadoop.fs.s3a.path.style.access  true
# spark rest
spark.sql.extensions               org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.rest             org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.rest.catalog-impl    org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.rest.io-impl    org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.rest.uri        http://10.0.162.5:30299
spark.sql.catalog.rest.warehouse   s3://warehouse/
spark.sql.catalog.rest.token       123456
spark.sql.catalog.rest.s3.endpoint    http://10.0.162.26:39999/api/v1/s3
spark.sql.catalog.rest.s3.path-style-access    true
spark.sql.defaultCatalog     rest

```
